name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker login
      uses: docker/login-action@v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the Docker image and Push
      uses: docker/build-push-action@v7.1.0
      with:
        context:
        push: true
        tags: ghcr.io/freny11/project1:latest
   
        
